### ISSUE TITLE
Incorrect release number displayed in the console for release 0.2.0

### ISSUE THREAD

**Issue by florentbr** [operasoftware/operachromiumdriver#10]
The release number displayed in the console doesn't match the release number:
 Displayed : Starting Opera driver beta 0.1
 Expected: Starting Opera driver 0.2.0

Environment: Windows 8.1 64, Opera driver 0.2.0

**Comment by paymand** [comment]
Fixed in [v0.2.2] (https://github.com/operasoftware/operachromiumdriver/releases/tag/v0.2.2).

**Comment by nartamonov** [comment]
@paymand Sorry, but it seems that issue is not fixed. I downloaded v0.2.2 release ([windows x64 edition](https://github.com/operasoftware/operachromiumdriver/releases/download/v0.2.2/operadriver_win64.zip)) but version is wrong:

```
C:\Users\qa_local>operadriver --version
OperaDriver 0.2.0 (ba47709ed9e35ce26dbd960fb5d75be104290d96)
C:\Bin>dir /l
24.04.2015  14:52         7 104 000 operadriver.exe
```

**Comment by paymand** [comment]
@nartamonov: I'm not in charge of this project anymore. @andreasbovens might be able to help.

**Comment by wladzynski** [comment]
Latests release reports proper operadriver version. 
https://github.com/operasoftware/operachromiumdriver/releases/tag/v.2.27
